stages:
  split:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw_data/raw.csv
    - src/data/make_dataset.py
    outs:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - data/processed_data/y_train.csv
    - data/processed_data/y_test.csv
  normalize:
    cmd: python src/data/normalize_train_test.py
    deps:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    outs:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/X_test_scaled.csv
  gridsearch:
    cmd: python src/models/best_params.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    outs:
    - models/ridge_best_params.pkl
  training:
    cmd: python src/models/train_model.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/ridge_best_params.pkl
    outs:
    - models/ridge_trained.pkl
  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
    - models/ridge_best_params.pkl
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    outs:
    - data/predictions.csv
    metrics:
    - metrics/scores.json